// English-only copy for the portfolio.
export const DICT = {
    "picker.season": "Season",
    "seasons.spring": "Spring", "seasons.summer": "Summer", "seasons.autumn": "Autumn", "seasons.winter": "Winter",
    "nav.aria": "Sections", "nav.home": "Home", "nav.stack": "Skills", "nav.project": "Project", "nav.contact": "Contact",
    "header.availability": "Open to opportunities",
    "hero.greeting": "Hi, I am", "hero.roleLine": "Software Developer.", "hero.tagline": "I build full-stack applications that turn real needs into useful, reliable software. My work brings together Java, Spring Boot, React, databases, and practical AI features.", "hero.cv": "View Resume", "hero.hire": "Contact me", "hero.scroll": "Scroll to explore", "hero.keysHint": "· hover over the keys",
    "nav.about": "About",
    "about.kicker": "about me", "about.title": "A developer who enjoys solving real problems.",
    "about.body1": "I studied Information Technology at Oriental Institute of Science and Technology in Bhopal, where I built a foundation in object-oriented programming, data structures, databases, and software design. I enjoy taking an idea from its first requirements through the API, data model, and user interface, with an emphasis on clear code and useful experiences.",
    "about.body2": "From February to May 2026, I worked as a Software Engineer Intern at Evendri.in on a direct-to-consumer e-commerce platform. I contributed to product discovery and detail pages, and worked on checkout integrations for UPI, cards, and cash on delivery. That experience helped me connect backend and frontend decisions to the needs of a real product.",
    "about.body3": "My personal projects explore secure role-based workflows, REST APIs, and AI features using the Gemini API. I have also solved more than 200 data-structures and algorithms problems across coding platforms and led a six-member team in delivering project milestones. I’m continuing to grow as a developer and am interested in building thoughtful software with a collaborative team.",
    "stack.title": "Technical Skills", "stack.hint": "(hint: hover over a key)", "stack.hintMobile": "The tools I use to build reliable applications.",
    "projects.kicker": "project", "projects.viewMore": "View details", "projects.openSite": "Visit live project", "projects.viewCode": "View code", "projects.close": "Close", "projects.stackLabel": "Technology",
    "contact.kicker": "contact", "contact.title": "Let’s build something useful.", "contact.body": "I’m open to software engineering roles and collaborative projects where I can contribute across backend services, web interfaces, and data-driven features. If you’re working on a problem that could use a thoughtful, hands-on developer, I’d be glad to talk.", "contact.copyEmail": "Copy email", "contact.openMail": "Send email", "contact.github": "GitHub", "contact.linkedin": "LinkedIn", "contact.emailToast": "Email copied", "contact.footer": "© 2026 Aditya Anjne. All rights reserved.",
    "keyboard.taglines.java": "Object-oriented foundations for robust applications.", "keyboard.taglines.python": "A versatile language for problem-solving and automation.", "keyboard.taglines.javascript": "Interactive experiences for the web.", "keyboard.taglines.html5": "The semantic structure behind every page.", "keyboard.taglines.css": "Responsive, polished interfaces.", "keyboard.taglines.react": "Reusable components for modern web apps.", "keyboard.taglines.springboot": "Enterprise-ready Java applications.", "keyboard.taglines.hibernate": "Persistence made practical with JPA.", "keyboard.taglines.mysql": "Relational data designed to perform.", "keyboard.taglines.oracledb": "Enterprise relational database management.", "keyboard.taglines.git": "Clear history and collaborative development.", "keyboard.taglines.github": "Sharing and shipping projects.", "keyboard.taglines.postman": "Testing APIs with confidence.", "keyboard.taglines.googlegemini": "Generative AI for useful product features.", "keyboard.taglines.githubcopilot": "AI-assisted development for faster iteration.",
};
export function translate(path) { return DICT[path] ?? path; }
